### ISSUE TITLE
Waiting for: Bun features

### ISSUE THREAD

**Issue by bndkt** [bndkt/kotekan#11]
- [x] react-server import condition (https://github.com/oven-sh/bun/issues/8990)
- [ ] Bun edge runtime (https://github.com/oven-sh/bun/issues/159)
- [ ] Hot reload for Bun.spawn (https://github.com/oven-sh/bun/issues/9556)
- [ ] Module federation (https://github.com/oven-sh/bun/discussions/4653)
